# Generated by Django 3.2.16 on 2024-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ended',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='visit',
            name='started',
            field=models.DateField(default=None),
        ),
    ]
