# Generated by Django 3.2.16 on 2024-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20240406_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ended',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='started',
            field=models.DateField(null=True),
        ),
    ]
