# Generated by Django 3.2.16 on 2024-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20240407_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
