# Generated by Django 3.2.16 on 2024-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_visit_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
